import LocalizedStrings from "react-native-localization";
const strings = new LocalizedStrings({
    vn: {
        home: "Trang chủ",
        news: "Tin tức",
        notifications: "Thông báo",
        profile: "Thông tin",
        // Home Display
        schedule: "Thời khóa biểu",
        scoreboard: "Xem điểm",
        exam: "Lịch thi",
        homework: "Bài tập",
        tuition: "Học phí",
        ctxh: "Ngày CTXH",
        all: "Tất cả",
        recent_activity: "Hoạt động gần đây",
        utilities: "Tiện ích",
        // Schedule
        time: "Thời gian",
        room: "Phòng học",
        day_off: "Ngày nghỉ",
        lecturer: "Giảng viên",
        // Modal Select Language
        select_language: "Chọn ngôn ngữ",
        english: "Tiếng anh",
        vietnamese: "Tiếng việt",
        confirm: "Xác nhận",
        // Profile Display
        language: "Ngôn ngữ",
        setting: "Cài đặt",
        student_information: "Thông tin sinh viên",
        information: "Thông tin",
        account:"Tài khoản",
        terms_of_use: "Điều khoản sử dụng",
        QuestionAndAnswer: "Hỏi đáp về ứng dụng",
        usage_rules_and_policy: "Quy định sử dụng và chính sách người dùng",
        privacy_policy: "Chính sách quyền riêng tư",
        basic_information: "Thông tin cơ bản",
        contact_information: "Thông tin liên hệ",
        course_information: "Thông tin khóa học",
        full_name: "Họ và tên",
        email: "Email",
        student_id: "MSSV",
        date_of_birth: "Ngày sinh",
        place_of_origin: "Nguyên quán",
        phone: "Điện thoại",
        personal_email: "Email cá nhân",
        course: "Khóa học",
        school_year: "Niên khóa",
        education_program: "Chương trình đào tạo",
        class: "Lớp",
        sign_out: "Đăng xuất",
        no_data:"Không có dữ liệu",
        // Scoreboard
        year: "Năm học",
        semester: "Học kỳ",
        Overall_GPA: "Điểm trung bình toàn khóa",
        Overall_Semester: "Điểm trung bình học kỳ",
        Overall_Year: "Điểm trung bình năm",
        Compare_the_same_period: "So sánh cùng kỳ",
        passed_credits: "Số tín chỉ đã đậu",
        GPA: "Điểm trung bình",
        Activity_Score: "Điểm rèn luyện",
        classification: "Xếp loại học lực",
        // Exam
        exam_date: "Ngày thi",
        examination_room: "Phòng thi",
        first_year: "Năm 1",
        second_year: "Năm 2",
        third_year: "Năm 3",
        fourth_year: "Năm 4",
        first_semester: "Học kỳ 1",
        second_semester: "Học kỳ 2",
        summer_semester: "Học kỳ hè",
        // Homework
        things_to_do: "Việc cần làm",
        late_deadline: "Trễ deadline",
        // News
        contact: "Liên hệ",
        general: "Tổng hợp",
        website: "Website",
        fanpage: "Fanpage",
        // Notifications
        remind: "Nhắc nhở",
        update: "Cập nhật",
        watch_now: "Xem ngay",
        answer: "Trả lời",
        no_corresponding_data: "Không có dữ liệu tương ứng",
        // Tuition
        paid: "Đã thanh toán",
        owed: "Còn nợ",
        unpaid:"Chưa thanh toán",
    },
    en: {
        home: "Home",
        news: "News",
        notifications: "Notifications",
        profile: "Profile",
        // Home Display
        schedule: "Schedule",
        scoreboard: "Scoreboard",
        exam: "Exam schedule",
        homework: "Homework",
        tuition: "Tuition",
        ctxh: "Social work day",
        all: "All",
        recent_activity: "Recent activities",
        utilities: "Utilities",
        // Schedule
        time: "Time",
        room: "Room",
        day_off: "Day off",
        lecturer: "Lecturer",
        // Modal Select Language
        select_language: "Choose a language",
        english: "English",
        vietnamese: "Vietnamese",
        confirm: "Confirm",
        // Profile Display
        language: "Language",
        setting: "Setting",
        student_information: "Student's information",
        information: "Information",
        account:"Account",
        terms_of_use: "Terms of use",
        QuestionAndAnswer: "Q&A",
        usage_rules_and_policy: "Usage rules and policy",
        privacy_policy: "Privacy policy",
        basic_information: "Basic information",
        contact_information: "Contact information",
        course_information: "Course information",
        full_name: "Full name",
        email: "Email",
        student_id: "Student's ID",
        date_of_birth: "Date of birth",
        place_of_origin: "Place of origin",
        phone: "Phone",
        personal_email: "Personal email",
        course: "Course",
        school_year: "School year",
        education_program: "Education program",
        class: "Class",
        sign_out: "Sign out",
        no_data:"No data",
        // Scoreboard
        year: "Year",
        semester: "Semester",
        Overall_GPA: "Overall GPA",
        Overall_Semester: "Semester GPA",
        Overall_Year: "Year GPA",
        Compare_the_same_period: "Compare the same period",
        passed_credits: "Number of passed credits ",
        GPA: "Grade Point Average",
        Activity_Score: "Activity score",
        classification: "Classification",
        // Exam
        exam_date: "Exam date",
        examination_room: "Examination room",
        first_year: "1st year",
        second_year: "2nd year",
        third_year: "3rd year",
        fourth_year: "4th year",
        first_semester: "1st semester",
        second_semester: "2nd semester",
        summer_semester: "Summer semester",
        // Homework
        things_to_do: "Things to do",
        late_deadline: "Late deadline",
        // News
        contact: "Contact",
        general: "General",
        website: "Website",
        fanpage: "Fanpage",
        // Notifications
        remind: "Remind",
        update: "Update",
        watch_now: "Watch now",
        answer: "Answer",
        no_corresponding_data: "No corresponding data",
        // Tuition
        paid: "Paid",
        owed: "Owed",
        unpaid:"Unpaid",
    },

});
export default strings;
const changeLaguage = (languageKey) => {
    strings.setLanguage(languageKey)
}